In [2]:
import pandas as pd
import numpy as np
import os
import re

In [2]:
directory = "rawdata/air_data"

#loop through data folder and open each file as csv. take name from disease code
df_list = []
title_list = []
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)

    # checking if it is a file
    if os.path.isfile(f):
        print(filename)
        title = filename
        print(title)
        title_list.append(title)
        if filename.split('.')[1] == "csv":
            df = pd.read_csv(f) 
            print(df.head())  
        elif filename.split('.')[1] == "xlsx":
            df = pd.read_excel(f)
            print(df.head())  
        #append df to df list regardless of f type
        df_list.append(df)
        #print(title[:4])

FileNotFoundError: [Errno 2] No such file or directory: 'rawdata/air_data'

In [6]:
out1 = "air_data_precovid"
out2 = "air_data_postcovid"
for filename, df in zip(title_list, df_list):
    title = filename.split(".")[0]
    df['Classification(1)']= df['Classification(1)'].ffill()
    filtered_df = df[(df['Classification(1)'] == df['Classification(2)']) | df['Classification(2)'].str.contains('Average')]
    filtered_df.drop(["Classification(2)"], axis = 1, inplace=True)
    filtered_df.rename(columns = {"Classification(1)":"region"}, inplace = True)

    filtered_df['region'] = filtered_df['region'].map(lambda x: x.replace("Sejong-si", "Sejong").replace("Jeju Special Self-governing Province", "Jeju"))

    
    final = filtered_df.transpose()
    col_ax = final.iloc[0, :]
    final = final.iloc[1:].set_axis(col_ax, axis=1)
    if "2017_2019" in title:
        out = out1
    else:
        out = out2
    print(out)
    os.makedirs(out, exist_ok=True)  
    out_path = os.path.join(out, title + ".csv")
    final.to_csv(out_path)

In [ ]:
#concat files ending with 2017_2019 with the same pollutant
#we get data from 2017 to 2022
#do this only if the corresponding file has data starting from 2020

In [8]:
#loop through things in air_data_postcovid
#if first row contains 2017, skip 
#else 
#concat on row

directory = "rawdata/air_data_postcovid"
out = "rawdata/air_data"

for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    title = filename.split(".")[0]

    # checking if it is a file
    if os.path.isfile(f):
        df = pd.read_csv(f) 
        idx = df.iloc[:, 0]
        if not idx[0] == "2017.01":
            #find file that contains the same pollutant name from air_data_precovid
            precovid_dir = "air_data_precovid"
            f2 = f = os.path.join(precovid_dir, title + "_2017_2019.csv")
            df2 = pd.read_csv(f) 
            out_df = pd.concat([df2, df])
            out_df.head()
        else:
            out_df = df
    
    os.makedirs(out, exist_ok=True)  
    out_path = os.path.join(out, title + ".csv")
    out_df.to_csv(out_path)
            
       # df.set_index()

FileNotFoundError: [Errno 2] No such file or directory: 'rawdata/air_data_postcovid'

In [36]:
finedust_df = pd.read_csv('air_data/pm10.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'air_data/pm10.csv'

In [44]:
pm25 = pd.read_excel('rawdata/pm25raw.xlsx')
pm25.head()

/Users/seohyeonlee/p-ollution/.venv/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Classification(1),Classification(2),Classification(3),Classification(4),2020.01,2020.02,2020.03,2020.04,2020.05,2020.06,2020.07,2020.08,2020.09,2020.10,2020.11,2020.12
0,Urban atmosphere,Seoul,Jung-gu,Jung-gu,33,32,28,23,20,22,15,18,13,19,26,29
1,NaN,NaN,Jongno-gu,Jongno-gu,31,29,25,21,19,21,14,15,12,18,24,28
2,NaN,NaN,Jungnang-gu,Jungnang-gu,22,23,24,19,18,21,14,15,11,17,22,24
3,NaN,NaN,Dongdaemun-gu,Dongdaemun-gu,26,25,20,17,15,19,12,14,11,17,25,29
4,NaN,NaN,Eunpyeong-gu,Eunpyeong-gu,24,26,24,20,20,21,13,13,9,15,22,25

In [53]:
#pm25.apply(pd.to_numeric, errors='ignore') # turns all numbers into nan for some reason

pm25.isna().sum() # no missing values
pm25.shape
(pm25 == '-').sum().sum()
idxs = list(np.where(pm25 == "-"))
(pm25.isin('*')).sum().sum()

TypeError: only list-like or dict-like objects are allowed to be passed to DataFrame.isin(), you passed a 'str'

In [55]:
#clean missing or weir ddata

from supportFunctions import *
#pm25 = cleanData(pm25)
pm25[:20]

,Classification(1),Classification(2),Classification(3),Classification(4),2020.01,2020.02,2020.03,2020.04,2020.05,2020.06,2020.07,2020.08,2020.09,2020.10,2020.11,2020.12
0,Urban atmosphere,Seoul,Jung-gu,Jung-gu,33,32,28,23,20,22,15,18,13,19,26,29
1,NaN,NaN,Jongno-gu,Jongno-gu,31,29,25,21,19,21,14,15,12,18,24,28
2,NaN,NaN,Jungnang-gu,Jungnang-gu,22,23,24,19,18,21,14,15,11,17,22,24
3,NaN,NaN,Dongdaemun-gu,Dongdaemun-gu,26,25,20,17,15,19,12,14,11,17,25,29
4,NaN,NaN,Eunpyeong-gu,Eunpyeong-gu,24,26,24,20,20,21,13,13,9,15,22,25
5,NaN,NaN,Mapo-gu,Mapo-gu,31,28,25,20,17,20,14,15,11,17,24,26
6,NaN,NaN,Yeongdeungpo-gu,Yeongdeungpo-gu,29,27,25,19,16,20,14,16,11,18,25,27
7,NaN,NaN,Dongjak-gu,Dongjak-gu,32,31,28,23,20,21,15,16,12,19,24,28
8,NaN,NaN,Gwanak-gu,Gwanak-gu,28,27,23,18,17,20,13,14,10,17,21,22
9,NaN,NaN,Gangnam-gu,Gangnam-gu,28,25,26,21,19,22,15,17,12,17,24,28
10,NaN,NaN,Geumcheon-gu,Geumcheon-gu,33,29,26,21,18,21,15,16,13,20,27,28
11,NaN,NaN,Gangdong-gu,Gangdong-gu,33,32,26,22,19,22,14,16,12,19,27,32
12,NaN,NaN,Gangbuk-gu,Gangbuk-gu,30,29,25,21,19,22,14,17,11,17,23,27
13,NaN,NaN,Seongbuk-gu,Seongbuk-gu,27,27,23,19,18,20,13,12,9,15,21,24
14,NaN,NaN,Yongsan-gu,Yongsan-gu,29,27,23,20,18,21,14,15,11,16,21,23
15,NaN,NaN,Gwangjin-gu,Gwangjin-gu,23,27,24,20,20,21,12,14,9,16,24,27
16,NaN,NaN,Seongdong-gu,Seongdong-gu,29,27,25,20,19,23,14,16,12,17,24,26
17,NaN,NaN,Dobong-gu,Dobong-gu,25,28,23,19,19,20,13,10,8,16,23,28
18,NaN,NaN,Seodaemun-gu,Seodaemun-gu,25,29,27,21,22,18,10,9,9,17,22,23
19,NaN,NaN,Guro-gu,Guro-gu,29,30,27,22,25,18,10,9,8,15,27,27

In [58]:
mask = pm25 == "-"
result = pm25[mask]
print(result)

    Classification(1) Classification(2) Classification(3) Classification(4)  \
0                 NaN               NaN               NaN               NaN
1                 NaN               NaN               NaN               NaN
2                 NaN               NaN               NaN               NaN
3                 NaN               NaN               NaN               NaN
4                 NaN               NaN               NaN               NaN
..                ...               ...               ...               ...
575               NaN               NaN               NaN               NaN
576               NaN               NaN               NaN               NaN
577               NaN               NaN               NaN               NaN
578               NaN               NaN               NaN               NaN
579               NaN               NaN               NaN               NaN

    2020.01 2020.02 2020.03 2020.04 2020.05 2020.06 2020.07 2020.08 2020.09  \
0       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
1       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
2       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
3       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
4       NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
575     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
576     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
577       -       -       -       -       -       -     NaN     NaN     NaN
578     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
579     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

    2020.10 2020.11 2020.12
0       NaN     NaN     NaN
1       NaN     NaN     NaN
2       NaN     NaN     NaN
3       NaN     NaN     NaN
4       NaN     NaN     NaN
..      ...     ...     ...
575     NaN     NaN     NaN
576     NaN     NaN     NaN
577     NaN     NaN     NaN
578     NaN     NaN     NaN
579     NaN     NaN     NaN

[580 rows x 16 columns]

In [66]:
#rename classifications 1-4 to Type, Region, Subregion1, Subregion2
#group by region and average everything
#correlate with diseases

pm25 = pm25.rename({"Classification(1)":"Type", "Classification(2)":"Region", "Classification(3)":"Subregion_1","Classification(4)":"Subregion_2"}, axis = 1)
region = pm25['Region'].ffill()
type = pm25['Type'].ffill()

pm25['Region'] = region
pm25['Type'] = type

pm25.head()

# pm25.iloc[:, 4:].head()
# pm25_filtered = pm25.iloc[4:, :].set_index(region).astype('float64')

# pm25_filtered.groupby(['Region']).mean()

,Type,Region,Subregion_1,Subregion_2,2020.01,2020.02,2020.03,2020.04,2020.05,2020.06,2020.07,2020.08,2020.09,2020.10,2020.11,2020.12
0,Urban atmosphere,Seoul,Jung-gu,Jung-gu,33,32,28,23,20,22,15,18,13,19,26,29
1,Urban atmosphere,Seoul,Jongno-gu,Jongno-gu,31,29,25,21,19,21,14,15,12,18,24,28
2,Urban atmosphere,Seoul,Jungnang-gu,Jungnang-gu,22,23,24,19,18,21,14,15,11,17,22,24
3,Urban atmosphere,Seoul,Dongdaemun-gu,Dongdaemun-gu,26,25,20,17,15,19,12,14,11,17,25,29
4,Urban atmosphere,Seoul,Eunpyeong-gu,Eunpyeong-gu,24,26,24,20,20,21,13,13,9,15,22,25

In [79]:
df = pm25

missing = df[(df == '-').any(axis=1)]
t = missing.iloc[:, 4:].set_index(missing['Region'])
missing_points = t.groupby(['Region']).agg('count').mean(axis = 1)

In [81]:
pm25_filtered = pm25.iloc[:, 4:].set_index(pm25['Region'])
subcategories = pm25_filtered.groupby(['Region']).agg('count').mean(axis = 1)

missing_rate = missing_points / subcategories
missing_rate

Region
Busan        0.156250
Chungbuk     0.354839
Chungnam     0.225000
Daegu        0.111111
Daejeon      0.071429
Gangwon      0.323529
Gwangju      0.400000
Gyeongbuk    0.456522
Gyeonggi     0.223140
Gyeongnam    0.232558
Incheon      0.277778
Jeju              NaN
Jeonbuk      0.333333
Jeonnam      0.139535
Sejong            NaN
Seoul             NaN
Ulsan        0.238095
dtype: float64

In [ ]:
#jeju, sejong and seoul have no missing data
#work on these places first

In [135]:
none_missing = pm25[pm25['Region'].isin(['Jeju', 'Seoul', 'Sejong'])]
f = none_missing.drop(['Type', 'Subregion_1', 'Subregion_2'], axis = 1)
idx = f['Region']
f.set_index(idx, inplace = True, drop = True)
f.drop('Region', axis = 1)

newf = f.applymap(lambda x: str(x).replace("*", ""))

res = newf.iloc[:, 1:].astype('float64').groupby('Region').mean().transpose()
res.rename({'Region':"yr-month"}, axis = 1)

/var/folders/lq/dt070ydd3h13pqgrgy6rpv300000gn/T/ipykernel_10731/2652681559.py:7: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  newf = f.applymap(lambda x: str(x).replace("*", ""))

Region     Jeju  Sejong      Seoul
2020.01  19.250   30.75  29.000000
2020.02  21.125   27.75  28.195122
2020.03  15.625   23.50  25.121951
2020.04  18.250   17.75  20.682927
2020.05  19.375   14.00  19.390244
2020.06  14.375   16.50  21.000000
2020.07  10.125    8.75  13.926829
2020.08  15.375   11.00  14.804878
2020.09  12.500   10.25  10.365854
2020.10  15.250   19.25  16.024390
2020.11  12.500   25.00  22.731707
2020.12  13.375   28.25  27.146341